- lib/diffHandler.js
Update git config with quotepath off, to prevent non-ASCII file names from being printed in quoted octal notation (which would cause the script to fail if a file name contains special characters)
> Set git quotepath off

- lib/service/inFolderHandler.js
Use escaping function from https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions
And also check if repo is dot to not append it... If someone has a more elegant way to do it please rise your hand
> Escape path into Regexp

- lib/metadata/a48.json
- lib/metadata/v46.json
Fixing Typo (removing the extra "e" in businessProcess**e**)
> Fix businessProcess metadata name

- __tests__/unit/lib/service/standardHandler.test.js
- lib/service/inResourceHandler.js
- lib/service/standardHandler.js
Improve the way to get the element name in order to build the member in the package.xml correctly depending the type of the element
> Fix quick action generation in the package.xml

- CONTRIBUTING.md
- README.md
- __tests__/unit/lib/service/inFileHandler.test.js
- lib/service/inFileHandler.js
---
---
Fix the building of the destructiveChanges.xml file for inFile metadata type (SharingRule, WorkflowRule and CustomLabel) when deleting the file.
The destructiveChanges contains also the metadata containing the inFile subtype which create an issue when deploying the destructiveChanges.xml.
We could have just kept the file deletion and not take care of the inFile but we decided to be more verbose and to delete explicitly what was tracked in the repository instead of the whole file. 
It allow to delete only what is tracked and so everything that should be in the file but are just in the org will not be deleted 
---
#38 
---
**Operating System:** Mac OS Mojave version 10.14.6
**NPM version:** 6.14.5
**Node version:** v14.5.0
**sgd version:** latest
> Remove standardHelper deletion usage for inFile destructiveChanges building

- lib/service/inFileHandler.js
Convert parsed XML to JSON array when it contains only one element
---
---
XML to JSON converter create JSON object for element containing one element
The code execute on array so it needs to put json objet into an array   when subtype contains only one element
---
fix #54 
---
**Operating System:** Mac OS Mojave 10.14.6
**NPM version:** 6.14.8
**Node version:** v14.11.0
**sgd version:** 3.3.1
**git version:** 2.28.0
> Fix XML parsing strict behavior

- bin/cli
---
---
Before today -i parameter was handled this way: 
- -i not set => ignore with default ./.forceignore
- -i set => ignore with default ./.forceignore
- -i set with value => ignore with value
Here are the changes on the way the -i parameter is handled
- -i not set => **do not ignore**
- -i set => ignore with default ./.forceignore
- -i set with value => ignore with value
---
**Operating System:** Mac OS Mojave 10.14.6
**NPM version:** 6.14.8
**Node version:** v14.11.0
**sgd version:** 3.3.1
**git version:** 2.28.0
> Improve ignore parameter handling

- __tests__/unit/lib/packageConstructor.test.js
- bin/cli
- src/commands/sgd/source/delta.ts
- src/utils/packageConstructor.js
This Pull Request allow to have output attribute always set in a consistant manner
   | Target Success | Target Failure
-- | -- | --
error |  null | error message
output | program.output | program.output
success | TRUE | FALSE
warning | [warning messages] | []
Also put CustomObject type at the top of the {package|destructiveChanges}.xml
---
---
Fix the initial value for the warning attributes in the cli file and sfdx plugin file
Create custom sort to move 'CustomObject' type on top of the type list
---
fixes #74 
---
_(Write your answer here.)_
---
_(Write your answer here.)_
---
**Operating System:** Mac Mojave 10.14.6
**Yarn version:** 1.22.10
**Node version:** v15.2.1
**sgd version:** 4.0.3
**git version:** 2.29.2
> Output consistency

- README.md
---
---
This is only a documentation update. This pull request doesn't change the functionality for this plugin.
The correct name of the XML file which contains the deleted metadata is `destructiveChanges.xml` and the correct name of folder which contains this XML file is `destructiveChanges`.
---
No.
---
N/A
---
N/A
---
**Operating System:** macOS Big Sur (11.0.1)
**Yarn version:** N/A
**Node version:** v12.14.0
**sgd version:** N/A
**git version:** 2.27.0
> Fixed file and folder name on README.md

- README.md
Updating the readme to point to the repo with the following disclaimer (rather than pointing to the Dockerfile directly):
_"Please do not reference the mehdisfdc/sfdx-cli-gitlab image on your CI/CD pipeline, since this image may change at any time (which could break your pipeline).
If you are interested in using this image, please clone this repo and then create your own public image on https://hub.docker.com/ (it's free and easy, as of early 2021)."_
> Update link to example Dockerfile

- src/service/inFileHandler.js
---
---
Override the _fillPackage function
in order to apply template method pattern and benefit from parent func
This issue comes from a regression inserted by #102
---
closes #47 
- [X ] Jest test to check the fix is applied are added.
---
**node version:** v15.11.0
**git version:** 2.30.2
**sfdx version:** 7.85.1
**sgd plugin version:** 4.2.2
> Fix CustomLabels handling

- __tests__/functional.test.js
- src/main.js
---
---
Implement a post processing filtering to exclude element in
destructiveChanges.xml also present in package.xml
---
closes #111
---
**node version:** v15.12.0
**git version:** 2.31.0
**sfdx version:** sfdx-cli/7.93.1 darwin-x64 node-v15.12.0
**sgd plugin version:** sfdx-git-delta 4.2.3
> Make sure destructiveChanges.xml does not contains package.xml element

- src/service/inFileHandler.js
---
---
Deal with added files the same as modified ones.
Previously the code red the information from the file in the file system for added file.
Which is inaccurate when the `--to` parameter is different of the HEAD.
This PR define the content of package.xml (and delta generation content) from the diff (not from the content of the current file)
---
closes #47
---
**node version:** v15.12.0
**git version:** 2.31.0
**sfdx version:** sfdx-cli/7.93.1 darwin-x64 node-v15.12.0
**sgd plugin version:** sfdx-git-delta 4.2.3
> Fix Custom Label Addition package.xml generation

- README.md
- __tests__/unit/lib/utils/repoGitDiff.test.js
- bin/cli
- messages/delta.js
- src/commands/sgd/source/delta.ts
- src/utils/repoGitDiff.js
---
---
Add --ignore-destructive parameter to the cli
When specified it will override --ignore (if specified) and filter Deletion diff allowing to not have element in the ignore file added in the destructiveChanges
---
closes #98
---
New parameter is added `--ignore-destructive [-D]`
When specified it will override --ignore (if specified) and filter Deletion diff allowing to not have element in the ignore file added in the destructiveChanges
---
**node version:** v15.12.0
**git version:** 2.31.0
**sfdx version:** sfdx-cli/7.93.1 darwin-x64 node-v15.12.0
**sgd plugin version:** sfdx-git-delta 4.2.3
> Add --ignore-destructive parameter

- __tests__/unit/lib/service/standardHandler.test.js
- src/service/inFileHandler.js
- src/service/inFolderHandler.js
- src/service/inResourceHandler.js
- src/service/standardHandler.js
---
---
Add a method to treat package member
Make sure path separator for those member is "/" whatever the path separator is for the running architecture (POSIX or WIN)
---
closes #127
---
The best is to do integration testing using Windows OS
---
Should be included in the next minor/patch release
---
**git version:** git version 2.31.1
**sfdx version:** node-v14.16.0
**sgd plugin version:** sfdx-git-delta 4.3.1
> fix: use "/" for package member separator

- __tests__/unit/lib/utils/repoGitDiff.test.js
- src/utils/repoGitDiff.js
---
---
Filter from deletion "case only" file renaming
```sh
A	force-app/main/default/objects/Test__c/fields/ABC__c.field-meta.xml
D	force-app/main/default/objects/Test__c/fields/abc__c.field-meta.xml
```
Should generate only a package.xml (and not the destructiveChanges.xml) containing
```xml
<?xml version="1.0" encoding="UTF-8"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
<types>
<members>Test__c.ABC__c</members>
<name>CustomField</name>
</types>    
<version>50.0</version>
</Package>
```
---
closes #132 
---
Can be taken in any next release
---
**git version:** git version 2.31.1
**sfdx version:** …
> feat: filter deletion for case insensitive file renaming

- __tests__/__utils__/testHandlerHelper.js
- __tests__/unit/lib/service/inFolderHandler.test.js
- src/metadata/a48.json
- src/metadata/v46.json
- src/metadata/v47.json
- src/metadata/v49.json
- src/metadata/v50.json
- src/service/inFolderHandler.js
---
---
Improve regex creating the document metadata members
Let it deals with the volatility of the extension based on the type of the file hosting the change (it can be either the file extension or the meta file)
Improve test for inFolder element
Improve assertion in test handler helper
---
closes #135 
---
**git version:** git version 2.31.1
**sfdx version:** sfdx-cli/7.98.0 darwin-x64 node-v14.16.0
**sgd plugin version:** sfdx-git-delta 4.4.0
> fix: document extension handling

- bin/cli
- package.json
- src/commands/sgd/source/delta.ts
- src/index.ts
- src/metadata/v51.json
---
---
Add API version 51 metadata file support
Add a script to upgrade API version metadata
Add an attribute in the package.json to store the latest current API
Bind this attribute in the code for API default value usage
---
Use the new script in the package.json.
It requires `jq` and `sponge` installed
```sh
$ yarn increment:apiversion
```
It will increment the attribute sfdc.latestApiVersion in the `package.json`
And create a new file in `src/metadata` for the new API version
It works in unix like environment
---
> If you need to do something twice, then you should automate it instead of doing it
> -- <cite>Smart Lazy guy</cite>
---
**node …
> feat: add api version 51

- README.md
Add a mention to the yq tool in the README, as a solution to transform the output from SGD.
closes #126
> docs: add mention to yq

- CONTRIBUTING.md
- README.md
- package.json
- src/metadata/v52.json
Upgrade supported Salesforce API version to v52.
> feat: upgrade api version to v52

- CONTRIBUTING.md
- README.md
- __tests__/integration/main.test.js
- package.json
- src/main.js
- src/utils/childProcessUtils.js
- src/utils/fileGitDiff.js
---
---
Remove the path treatment for git diff file reader
Add path sanity treatment of config object
---
closes #152
---
Smoke test + Unit test
---
---
It has been tested on both mac and windows
**Operating System:** Darwin Kernel Version 18.7.0: Mon May  3 20:41:19 PDT 2021; root:xnu-4903.278.68~1/RELEASE_X86_64 and Windows 10
**sfdx version:** sfdx-cli/7.105.0 darwin-x64 node-v14.16.0
**sgd plugin version:** 4.6.0
> fix: issue with path separator conversion in xml file and path portability

- src/utils/fileGitDiff.js
---
---
git [context](https://git-scm.com/docs/git-diff#Documentation/git-diff.txt---unifiedltngt) is now set to 200 (instead of 10000000000).
It allows very large file to
- not exceed the spawnSync buffer
- keep default spawnSync buffer (1024*1024)
- keep working for every infile metadata kind (200 of context line seems to be enough during the [tests](https://github.com/scolladon/sfdx-git-delta-reproduction-playground/tree/issue/47-again))
---
closes #47 (again)
---
Use yarn test
Use the [reproduction playground](https://github.com/scolladon/sfdx-git-delta-reproduction-playground/tree/issue/47-again)
---
Can be included in the next release
--- …
> fix: git context to not exceed spawn sync buffer for very large inFile metadata

- __mocks__/fast-xml-parser.js
- __tests__/integration/main.test.js
- __tests__/unit/lib/service/customObjectHandler.test.js
- __tests__/unit/lib/service/inFileHandler.test.js
- __tests__/unit/lib/service/inFolderHandler.test.js
- src/main.js
- src/service/inFileHandler.js
---
---
Use the xml library to detect malformed xml and then throw exception catched
Non blocking ! Output this in the warnings section.
---
closes #155
---
You can test it using the reproduction playground dedicated [branch](https://github.com/scolladon/sfdx-git-delta-reproduction-playground/tree/issue/155)
Or locally using node:
```sh
$ git fetch
$ git checkout fix/xml-error-handling
$ node bin/run sgd:source:delta ...
```
---
Can be included in the next release
---
**sfdx version:** sfdx-cli/7.107.0 darwin-x64 node-v14.16.0
**sgd plugin version:** 4.61
> fix: handle xml parsing issues gracefully

- CONTRIBUTING.md
- README.md
- __tests__/integration/main.test.js
- __tests__/unit/lib/utils/repoSetup.test.js
- src/main.js
- src/utils/repoSetup.js
---
---
Move the current repository when config.to is different than HEAD
In order to have the file and the version of the file related to the commit wanted
---
Nop
---
Use jest and node
---
Need to be roughly tested and also we need to look for other way to do it better
---
**sfdx version:** sfdx-cli/7.107.0 darwin-x64 node-v14.16.0
**sgd plugin version:** 4.61
> fix: -d usage with -t different than HEAD

- __tests__/unit/lib/service/typeHandlerFactory.test.js
- package.json
- src/service/customObjectHandler.js
- src/service/typeHandlerFactory.js
---
---
Make sure the "first possible type" is returned as soon as it is encountered in the path.
Implements lookahead possibility for path with types which can contains other types (ie: objects can contain fields also)
=> Implements fast loop exit with possible lookahead
---
closes #171 
---
---
Tested locally with the sfdx git delta playground
---
**yarn version:** 1.22.11
**git version:** git version 2.32.0
**sfdx version:** sfdx-cli/7.110.0 darwin-x64 node-v14.16.0
**sgd plugin version:** 4.7.1
> fix: wrong type detection in subfolders

- src/service/inFileHandler.js
---
---
Configure the xml parser so it does not parse node value and attribute value
---
closes #175 
---
---
No test have been added because there is no point in testing the vendor lib.
---
**Operating System:** Darwin Kernel Version 19.6.0: Tue Jun 22 19:49:55 PDT 2021; root:xnu-6153.141.35~1/RELEASE_X86_64
**yarn version:** 1.22.11
**sfdx version:** sfdx-cli/7.110.0 darwin-x64 node-v14.16.0
**sgd plugin version:** 4.7.2
> fix: truncated xml values

- __tests__/unit/lib/service/inResourceHandler.test.js
- src/service/inResourceHandler.js
---
---
fix the way we identify files contained in Resource metadata kind (staticresource, lwc, aura, experiences, waveTemplate) to be copied
---
closes #176 
---
---
Available for the next release
---
**Operating System:** Darwin Kernel Version 19.6.0: Tue Jun 22 19:49:55 PDT 2021; root:xnu-6153.141.35~1/RELEASE_X86_64
**yarn version:** 1.22.11
**sfdx version:** sfdx-cli/7.110.0 darwin-x64 node-v14.16.0
**sgd plugin version:** 4.7.2
> fix: inResource file identification

- src/metadata/a48.json
- src/metadata/v47.json
- src/metadata/v49.json
- src/metadata/v50.json
- src/metadata/v51.json
- src/metadata/v52.json
- src/service/inResourceHandler.js
- src/service/standardHandler.js
---
---
Make sure to copy meta file when the inResource have one
Make sure to copy base file for static resource when it is just file (not zip)
---
closes #176
~~- [ ] Jest test to check the fix is applied are added.~~
---
---
---
**Operating System:** Darwin Kernel Version 19.6.0: Tue Jun 22 19:49:55 PDT 2021; root:xnu-6153.141.35~1/RELEASE_X86_64
**yarn version:** 1.22.11
**sfdx version:** node-v14.16.0
**sgd plugin version:** 4.8.0
> fix: issue with inResource meta file not copied for corner cases

- README.md
- __tests__/unit/lib/utils/fileGitDiff.test.js
- __tests__/unit/lib/utils/repoGitDiff.test.js
- bin/cli
- messages/delta.js
- src/commands/sgd/source/delta.ts
- src/utils/fileGitDiff.js
- src/utils/gitConstants.js
- src/utils/repoGitDiff.js
Manage a new argument --permissivediff to add the following parameters to git diff call
```javascript
[
'--ignore-all-space',
'--ignore-blank-lines',
'--ignore-cr-at-eol',
'--word-diff-regex',
]
```
It allows to avoid detecting as a difference the indentation/spaces stuff
Fixes #184
> feat: permissive git diff parameter

- .lintstagedrc
- __tests__/unit/lib/utils/repoGitDiff.test.js
- src/main.js
- src/service/inTranslationHandler.js
- src/service/subCustomObjectHandler.js
- src/service/typeHandlerFactory.js
- src/utils/repoGitDiff.js
- src/utils/typeUtils.js
---
---
It builds a more complete base of comparison to detect which file is deleted, renamed, added, moved by taking part of the path containing available metadata type.
For exemple :
`force-app/main/default/objects/Account/fields/CustomField__c.field-meta.xml`
before the algorithm was taking `CustomField__c.field-meta.xml` as comparison element
now it takes `objects/Account/fields/CustomField__c.field-meta.xml`
which allow to have the same field for another object being manipulated by the plugin
---
closes #193
---
You can use the sgd reproduction playground branch [issue/193](https://github.com/scolladon/sfdx-git-delta-reproduction-playground/tree/issue/193) to test current version of sgd (4.9.0) against the one in this PR
---
Next release can be considered to ship this
---
**Operating …
> fix: issue when filtering same file name for different metadata

- README.md
- __mocks__/.forceinclude
- __mocks__/fs.js
- __tests__/integration/main.test.js
- __tests__/unit/lib/utils/cliHelper.test.js
- __tests__/unit/lib/utils/repoGitDiff.test.js
- bin/cli
- messages/delta.js
- package.json
- src/commands/sgd/source/delta.ts
- src/main.js
- src/utils/cliHelper.js
- src/utils/repoGitDiff.js
- yarn.lock
---
---
My team has a use case for always requiring certain files to be included in the package.xml (these include a generated class file and test). And these files change based off of values (i.e. CI build numbers, etc) with each job run. We don't want to be submitting a new commit with each job build, but we need to include these files in the package.xml for `source:deploy`. Using this solution, we can ensure that the generated files are always included (along with `git add -f`).
---
~~closes #~~
---
---
---
**Operating System:** Darwin Kernel Version 19.6.0: Tue Aug 24 20:28:00 PDT 2021; root:xnu-6153.141.40~1/RELEASE_X86_64
**yarn version:** 1.22.17
**node version:** v14.18.1
**git version:** git version 2.29.2
**sfdx version:** sfdx-cli/7.124.0 darwin-x64 node-v14.18.1
**sgd plugin …
> feat: add support for defining an --include file

- .github/workflows/pull-request.yml
It contains a change of target for our pull request CI workflow in order to be able to run PR lint for Pull Request created from forked repository
---
---
It uses the `pull_request_target` on attribut instead of the `pull_request`.
Explanation [here](https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows#pull_request_target)
> build: use `pull_request_target` for pull request ci

- src/utils/fileGitDiff.js
- src/utils/repoGitDiff.js
---
---
This fixes issue with very large code base that need to be parsed.
But it may fall into the buffer size issue which may not be enough on certain environment.
This should be [refactored to use stream, event, promise and async/await](https://github.com/scolladon/sfdx-git-delta/projects/1#card-75522144) to get rid of this buffer.
Change the buffer size for each call to `child_process.spawnSync`, set it to 10MB
The buffer is not set as a constant but each file defines the same value as each file may want to have a different value (`repoGitDiff` and `fileGitDiff`)
---
closes #192
---
Use a very large repository (>20k metadata element)
---
**Operating System:** Darwin Kernel Version 19.6.0: Sun Nov 14 19:58:51 PST 2021; root:xnu-6153.141.50~1/RELEASE_X86_64
**yarn version:** 1.22.15 …
> fix: spawn buffer size

- __mocks__/fs.js
- src/main.js
- src/metadata/metadataManager.js
- src/service/inFileHandler.js
- src/service/inResourceHandler.js
- src/utils/packageConstructor.js
- src/utils/repoGitDiff.js
- src/utils/typeUtils.js
---
Fix about `Object.hasOwn`  issue on main test
---
Fix about `Object.hasOwn` because it is not available on node 14
Rollback to use `Object.prototype.hasOwnProperty.call`
> fix: rollback using hasOwnProperty

- .github/workflows/pull-request.yml
And merging work when possible
---
---
Use pull_request instead of pull_request_base
Issue is pull_request_base checkout the base branch which is not what we want to do.
In order to not have issue with external check using our credential those steps are not done from fork
> fix: pull request CI base commit

- README.md
Update to the readme, taking into account that the `sfdx force:source:deploy` command [now supports](https://developer.salesforce.com/docs/atlas.en-us.sfdx_cli_reference.meta/sfdx_cli_reference/cli_reference_force_source.htm) `--predestructivechanges <filepath>` and `--postdestructivechanges <filepath>`
closes #240
> docs: add readme postdestructive section 

- __mocks__/fs-extra.js
- __tests__/unit/lib/service/customObjectHandler.test.js
- src/service/botHandler.js
- src/service/customObjectHandler.js
- src/service/inFolderHandler.js
- src/service/inResourceHandler.js
- src/service/subCustomObjectHandler.js
---
---
Fix the path resolution when copying master detail fields for custom object part of the delta generated sources
Now, when a custom object is should be deployed and is copied in the output folder, master detail fields of this object will also be copied
---
closes #263
---
You can test with the [playground](https://github.com/scolladon/sfdx-git-delta-reproduction-playground/tree/issue/263)
Or run the jest test
---
---
**Operating System:** Darwin Kernel Version 19.6.0: Thu Jan 13 01:26:33 PST 2022; root:xnu-6153.141.51~3/RELEASE_X86_64
**yarn version:** 1.22.15
**node version:** v14.19.0
**git version:** 2.35.1
**sfdx version:** sfdx-cli/7.142.1 darwin-x64 node-v14.19.0
**sgd plugin version:** 5.0.0
> fix: path resolution for master detail fields

- __mocks__/fast-xml-parser.js
- __mocks__/fs.js
- __tests__/__utils__/testHandlerHelper.js
- __tests__/functional.test.js
- __tests__/unit/lib/metadata/metadataManager.test.js
- __tests__/unit/lib/service/botHandler.test.js
- __tests__/unit/lib/service/customObjectHandler.test.js
- __tests__/unit/lib/service/inFileHandler.test.js
- __tests__/unit/lib/service/inFolderHandler.test.js
- __tests__/unit/lib/service/inResourceHandler.test.js
- __tests__/unit/lib/service/inTranslationHandler.test.js
- __tests__/unit/lib/service/standardHandler.test.js
- __tests__/unit/lib/service/subCustomObjectHandler.test.js
- __tests__/unit/lib/service/typeHandlerFactory.test.js
- __tests__/unit/lib/service/waveHandler.test.js
- __tests__/unit/lib/utils/packageConstructor.test.js
- src/main.js
- src/metadata/metadataManager.js
- src/service/inFileHandler.js
- src/service/inFolderHandler.js
- src/service/inResourceHandler.js
- src/service/standardHandler.js
- src/service/subCustomObjectHandler.js
- src/service/waveHandler.js
- src/utils/packageConstructor.js
- src/utils/repoGitDiff.js
- src/utils/typeUtils.js
---
---
Refactor the code to use Map instead of {} to benefit from [everything Map](https://medium.com/front-end-weekly/es6-map-vs-object-what-and-when-b80621932373) comes with
> refactor: use Map instead of {}

- README.md
- package.json
- src/utils/packageConstructor.js
- yarn.lock
---
---
Migrate from xmlBuilder to xmlBuilder2 for package.xml generation
xmlBuilder is not maintain anymore, so migrating to xmlBuilder2 is interesting to benefits from performance improvement and security issue fixes
> refactor: upgrade xmlBuilder to xmlBuilder2

- CONTRIBUTING.md
- __tests__/unit/lib/utils/repoGitDiff.test.js
- package.json
- src/metadata/v51.json
- src/metadata/v52.json
- src/metadata/v53.json
- src/metadata/v54.json
- src/service/inFolderHandler.js
- src/service/inResourceHandler.js
- src/service/standardHandler.js
- src/utils/metadataConstants.js
- src/utils/repoGitDiff.js
- yarn.lock
---
---
Fix `--numstat` binary interpretation support when parsing git diff lines
Fix `document` meta file copy issue
---
closes #270 
There is still an issue when changing an in Folder meta file, the corresponding file is not copied when the file extension is different
---
---
Next release
> fix: binary filtering for git diff --numstat parsing and document meta type file regression

- src/service/inResourceHandler.js
- src/service/standardHandler.js
---
---
Fix the way we use what is returned form `standardHandler._parseLine()` function.
The order of extraction of the array elements was not right in the `inRessourceHandler` which led to always detecting the path as existing and then add it in the package.xml instead
---
closes #280 
Not necessary
> fix: parseLine array result destructure selection

- __tests__/functional.test.js
- __tests__/integration/main.test.js
- __tests__/unit/lib/utils/cliHelper.test.js
- __tests__/unit/lib/utils/repoSetup.test.js
- src/utils/childProcessUtils.js
- src/utils/cliHelper.js
- src/utils/gitConstants.js
- src/utils/repoSetup.js
The 'from' and 'to' parameters will be verified to be valid git commits
---
---
---
closes #
---
---
---
**Operating System:** …
**yarn version:** …
**node version:** …
**git version:** …
**sfdx version:** …
**sgd plugin version:** …
> feat: verify `--from` and `--to` parameters to be valid git pointer

- README.md
- __tests__/unit/lib/utils/cliHelper.test.js
- src/utils/cliHelper.js
- src/utils/gitConstants.js
- yarn.lock
---
---
It allow tag git pointer to be reference in the `--to` and `--from` parameters
---
closes #282
> fix: allow 'tag' type git pointer

- README.md
Add conditional deplyment use case in the README, as a solution to solve deployment errors when delta files are empty.
closes #249
> docs: add conditional deployment use case to readme

- __tests__/unit/lib/utils/cliHelper.test.js
- __tests__/unit/lib/utils/repoSetup.test.js
- src/locales/en.js
- src/utils/cliHelper.js
- src/utils/repoSetup.js
---
---
Export error message to a dedicated file
Prepare for i18n
> feat: prepare i18n

- __tests__/unit/lib/service/standardHandler.test.js
- package.json
- src/metadata/v52.json
- src/metadata/v53.json
- src/metadata/v54.json
---
---
Add restriction rule metadata support for API 52, 53 and 54.
Shape of the metadata is based on the actual [documentation](https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/meta_restrictionrule.htm).
I also tested the format from a fresh scratch org to be sure:
---
closes #308
---
Create a restriction rule
Retrieve it 
Commit it
Run sgd and look at the result
---
**Operating System:** Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:37 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T6000
**yarn version:** 1.22.15
**node version:** v14.19.3
**git version:** 2.21.1
**sfdx version:** sfdx-cli/7.152.0 darwin-x64 node-v14.19.3
**sgd plugin version:** 5.2.0
> feat: add restriction rules metadata

- __tests__/unit/lib/service/subCustomObjectHandler.test.js
- src/metadata/a48.json
- src/metadata/v46.json
- src/metadata/v47.json
- src/metadata/v49.json
- src/metadata/v50.json
- src/metadata/v51.json
- src/metadata/v52.json
- src/metadata/v53.json
- src/metadata/v54.json
- src/metadata/v55.json
- src/service/typeHandlerFactory.js
- src/utils/metadataConstants.js
---
---
Add configuration to include Sub Custom Object Index metadata for big object
---
closes #327
> feat: add big object index support

- __mocks__/fs.js
- __tests__/unit/lib/utils/cliHelper.test.js
- src/utils/cliHelper.js
Fixes isGit method to check whether .git is a folder or file (this is the case on submodules)
---
---
It adds new condition on the isGit method that also checks whether a .git file exists
---
Locally
**Operating System:** MacOS Monterey
**yarn version:** 1.22.19
**node version:** 18.8.0
**git version:** 2.37.0
**sfdx version:** 7.166.1
**sgd plugin version:** …
> feat: enable git diff on submodules

- .github/workflows/manage-versions.yml
---
---
Use npm instead of yarn
Yarn is failing locally and is not reliable to manage version distribution
> fix: use npm instead of yarn to manage versions

- __tests__/unit/lib/utils/repoGitDiff.test.js
- src/utils/repoGitDiff.js
---
---
A regression as been inserted in the ignore feature at this [commit](https://github.com/scolladon/sfdx-git-delta/commit/a24536dec3d5356216558f1941a109c0a5ac28ba#diff-057ce4acbeadb39d45fbe732a7967768f68076460fad74168881b58c762135dcL180-R197)
It was not flagged by the unit test because it was testing a regex where the base of the file path did not matter.
The issue concerned ignore matcher for full path because it was not cleaning the type of the git operation of the line.
So instead of comparing just a path : `file/path/myfile.extension` it was comparing `M	file/path/myfile.extension`.
With full path matcher it cannot work.
The fix is simple, it just need to clean the git operation of the line to extract the file path and apply the ignore logic on that.
The unit test have been …
> fix: use file path with ignore patterns

- __tests__/unit/lib/post-processor/flowTranslationProcessor.test.js
- __tests__/unit/lib/service/inFolderHandler.test.js
- __tests__/unit/lib/service/inResourceHandler.test.js
- __tests__/unit/lib/service/inTranslationHandler.test.js
- __tests__/unit/lib/service/standardHandler.test.js
- __tests__/unit/lib/utils/fsHelper.test.js
- src/post-processor/flowTranslationProcessor.js
- src/service/customObjectHandler.js
- src/service/inFolderHandler.js
- src/service/inResourceHandler.js
- src/service/standardHandler.js
- src/utils/fsHelper.js
---
---
Fix home made git based `readDir` implementation and usage
`fs.readdir` [returns](https://nodejs.org/api/fs.html#fspromisesreaddirpath-options) a `fs.Dirent` data structure which tell us if the element is a folder or a file.
Using git to explore folder content returns string.
A element is a folder if it ends with '/'
Some part of the code relied on not having this slash at the end of a file.
Fix config parameter in `fsHelper`
Improve error handling in `fsHelper`
---
closes #413 
closes #414 
closes #416
---
Build a lwc component with subfolder (for test for example), modify the js file, check all the content of the module (even sub folder) is copied to output
[This playground](https://github.com/joernflath/sfdx-git-delta-reproduction-playground) can be used as well
[This …
> fix: readDir git based implementation

- .github/workflows/release.yml
---
Allow release workflow to push on the repo on behalf of the repo owner
---
Create a PAT, add it to the secrets and use it with github checkout.
Release workflow can then force push on the repo when a new release is done
> build: allow force push with protection rule in release workflow

- src/utils/fsHelper.js
---
Remove relative path definition based on source parameter when generating incremental source
`--source` parameter is already used to scope the content of the diff
At that moment only sources related to what is asked are sent to copy.
---
closes #416
---
Use the `--source` parameter
> fix: generate incremental (`-d`) with source (`-s`) parameter

- .github/workflows/on-main-push.yml
- .github/workflows/on-published-release.yml
- .github/workflows/on-pull-request.yml
- package.json
- yarn.lock
---
Make sure publish does not fails because of the tooling not installed
Just add the cache
Ensure the new version prompt is bypassed and we use the last version in the `package.json`
> fix: publish to npm automation

- .github/workflows/on-main-push.yml
- .github/workflows/on-published-release.yml
- package.json
---
Make sure release comments display correctly by removing escaped character
Also make sure release test installation is done with the version instead of the channel latest-rc
> fix: remove escaping in the published release message

- src/utils/fileGitDiff.js
- src/utils/gitConstants.js
- src/utils/repoGitDiff.js
- yarn.lock
---
Remove `--word-diff-regex=|[^[:space:]]` parameter when getting diff content of file (for custom labels or sharing rules or workflow rule for instance)
This parameter is working fine with `--numstat` and allow the plugin to get files that have been changed while ignoring whitespace changes
But it does not works when working with full diff content and was returning nothing is changed even when there are not blank characters changes
---
> fix: in file comparison while ignoring whitespace (#478

- __tests__/unit/lib/post-processor/flowTranslationProcessor.test.js
- src/post-processor/flowTranslationProcessor.js
---
Flow translation post processing was broken because it was not passing the right config variable to the `scanExtension` methods
This PR fix this issue and add more precise assertion to the related unit tests
> fix: flow translation post processing

- __tests__/unit/lib/utils/fileGitDiff.test.js
- src/utils/fileGitDiff.js
---
When rebuilding metadata contained in file like `Workflow` or `SharingRule`
Now the algorithm rebuild only what is tracked as metadata and leave other information untouched
> fix: keep attributs not subject to comparison

- __tests__/unit/lib/post-processor/flowTranslationProcessor.test.js
- src/post-processor/flowTranslationProcessor.js
---
Implement fast exit of `flowTranslationProcessor` when the changes detected does not have Flows as there is no point to look for translation then
---
~~closes #~~
> feat: fast `flowTranslationProcessor` exit

- src/service/inFolderHandler.js
- src/service/inResourceHandler.js
---
Fix the way we split the path of a line to get the parent folder
Make sure it works on any `path.sep` environment specificities
---
closes #548
> fix: get parent folder name portability

- .github/PULL_REQUEST_TEMPLATE.md
- __tests__/functional/delta.nut.ts
- package.json
- src/commands/sgd/source/delta.ts
- yarn.lock
---
Returned the result object so `--json` handler can use it to display result when the flag is set
---
closes #568
This fix will not handle the warning in the error array.
The git diff command in this case does not throw an error (exit code is 0) but write the warning message in `stderr`
We catch every error message from `stderr` to treat those as error and stop execution, by design.
> fix: how `--json` parameter output is handled

- src/metadata/v54.json
- src/metadata/v55.json
- src/metadata/v56.json
- src/metadata/v57.json
- src/metadata/v58.json
Fix for the issue -  https://github.com/scolladon/sfdx-git-delta/issues/650 - added TimelineObjectDefinition and UIObjectRelationConfig for version 57 and 58.
This PR related to the issue https://github.com/scolladon/sfdx-git-delta/issues/650
We are using Salesforce Health Cloud and git delta deployment. We are not seeing the support Health Cloud metadata objects e.g. [UIObjectRelationConfig](https://developer.salesforce.com/docs/atlas.en-us.health_cloud_object_reference.meta/health_cloud_object_reference/meta_uiobjectrelationconfig.htm), [TimelineObjectDefinition](https://developer.salesforce.com/docs/atlas.en-us.health_cloud_object_reference.meta/health_cloud_object_reference/meta_timelineobjectdefinition.htm)
---
closes #650 
---
---
> feat: add support for Health Cloud metadata

- src/metadata/v56.json
- src/metadata/v57.json
- src/metadata/v58.json
---
Add support for Net Zero Cloud metadata types per https://developer.salesforce.com/docs/atlas.en-us.netzero_cloud_dev_guide.meta/netzero_cloud_dev_guide/netzero_cloud_metadata_api_parent.htm for api version 57 and 58 (SustainabilityUom for v56).
ClauseCatgConfiguration
DisclosureDefinition
DisclosureDefinitionVersion
DisclosureType
FuelType
FuelTypeSustnUom
SustnUomConversion
SustainabilityUom  (56+)
---
No open issue.
---
---
> feat: add support for Net Zero Cloud metadata

- .github/workflows/on-main-push.yml
- .github/workflows/on-pull-request.yml
---
Add a new dimension to test with `sf-v2` in our e2e test at the PR level and in our release test at main push level
> ci: add sf-v2 dimension in e2e test and release test

- __tests__/unit/lib/metadata/metadataManager.test.ts
- src/metadata/metadataManager.ts
- src/metadata/v59.json
---
Add the metadata definition for v59
Change the logic to take the default latest supported version. It is now the second last
=> This will allow us support new version during preview period.
---
closes #696
> feat: add v59 metadata definition

- src/metadata/a48.json
- src/metadata/v47.json
- src/metadata/v49.json
- src/metadata/v50.json
- src/metadata/v51.json
- src/metadata/v52.json
- src/metadata/v53.json
- src/metadata/v54.json
- src/metadata/v55.json
- src/metadata/v56.json
- src/metadata/v57.json
- src/metadata/v58.json
- src/metadata/v59.json
---
Add `DocumentType` metadata support
This metadata is available since `v47`.
It is located in the `documentTypes` folder with the `documentType` suffix.
It does not have meta file associated
---
closes #443
> feat: add `DocumentType` metadata support

- src/metadata/v50.json
- src/metadata/v51.json
- src/metadata/v52.json
- src/metadata/v53.json
- src/metadata/v54.json
- src/metadata/v55.json
- src/metadata/v56.json
- src/metadata/v57.json
- src/metadata/v58.json
- src/metadata/v59.json
Adding 4 metadata types to the different metadata files to allow Einstein Prediction Builder delta deployments.
---
No Issue related to this.
---
an AI Model was created and deployed through VS Code with these files and it works so deltas will work as well, the  
directoryName, suffix and xmlName were triple checked with a local example.
inFolder and metaFile where set to false as I copied the connectedApps one.
---
> feat: adding prediction builder ai metadata types

- __tests__/unit/lib/utils/fsHelper.test.ts
- src/post-processor/flowTranslationProcessor.ts
- src/utils/fsHelper.ts
- src/utils/ignoreHelper.ts
---
Ensure ignore service is called when copying files
---
closes #744
> fix: apply ignore settings when copying file

- .eslintrc.js
- __tests__/integration/services.test.ts
- __tests__/unit/lib/post-processor/flowTranslationProcessor.test.ts
- __tests__/unit/lib/service/inFileHandler.test.ts
- __tests__/unit/lib/utils/cliHelper.test.ts
- __tests__/unit/lib/utils/fsHelper.test.ts
- __tests__/unit/lib/utils/fsUtils.test.ts
- __tests__/unit/lib/utils/ignoreHelper.test.ts
- package.json
- src/post-processor/flowTranslationProcessor.ts
- src/service/inResourceHandler.ts
- src/utils/cliHelper.ts
- src/utils/fsHelper.ts
- src/utils/fsUtils.ts
- src/utils/ignoreHelper.ts
- yarn.lock
---
Add circular dependency linting plugin
Fix discovered issues
> fix: circular dependency issues

- src/constant/fsConstants.ts
---
Use constant for path separator
> fix: use constant for path separator

- README.md
- __tests__/unit/lib/utils/fsUtils.test.ts
- src/adapter/GitAdapter.ts
- src/constant/fsConstants.ts
- src/utils/fsUtils.ts
---
Make sure leading and trailing path separated are kept
---
closes #814
> fix: absolute path handling

- .github/workflows/on-main-push.yml
- .github/workflows/on-pull-request.yml
- package.json
- yarn.lock
---
Fix perf test execution after having migrated to typescript
> build: fix perf test execution

- __tests__/integration/services.test.ts
- src/metadata/v46.json
- src/metadata/v47.json
- src/metadata/v49.json
- src/metadata/v50.json
- src/metadata/v51.json
- src/metadata/v52.json
- src/metadata/v53.json
- src/metadata/v54.json
- src/metadata/v55.json
- src/metadata/v56.json
- src/metadata/v57.json
- src/metadata/v58.json
- src/metadata/v59.json
- src/metadata/v60.json
- src/metadata/v61.json
- src/metadata/v62.json
---
Add metadata support for all three types of Feature Parameters:
- [FeatureParameterBoolean](https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/meta_featureparameterboolean.htm)
- [FeatureParameterDate](https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/meta_featureparameterdate.htm)
- [FeatureParameterInteger](https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/meta_featureparameterinteger.htm)
> feat: add FeatureParameter metadata support

- docs/migrating-to-v6.0.0.md
- src/metadata/v60.json
- src/metadata/v61.json
- src/metadata/v62.json
- src/service/typeHandlerFactory.ts
---
Add GenAI* Metadata support starting v60
---
closes #929
> feat: add new GenAI metadata definition

- src/metadata/v49.json
- src/metadata/v50.json
- src/metadata/v51.json
- src/metadata/v52.json
- src/metadata/v53.json
- src/metadata/v54.json
- src/metadata/v55.json
- src/metadata/v56.json
- src/metadata/v57.json
- src/metadata/v58.json
- src/metadata/v59.json
- src/metadata/v60.json
- src/metadata/v61.json
- src/metadata/v62.json
---
Support [ApexEmailNotification](https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/meta_apexemailnotifications.htm) metadata, starting v49 to current latest version (v62)
---
closes #933
> feat: support apexEmailNotification metadata

- src/metadata/a48.json
- src/metadata/v46.json
- src/metadata/v47.json
- src/metadata/v49.json
- src/metadata/v50.json
- src/metadata/v51.json
- src/metadata/v52.json
- src/metadata/v53.json
- src/metadata/v54.json
- src/metadata/v55.json
- src/metadata/v56.json
- src/metadata/v57.json
- src/metadata/v58.json
- src/metadata/v59.json
- src/metadata/v60.json
- src/metadata/v61.json
- src/metadata/v62.json
---
fix workflow knowledge publish decomposed sub type suffix
> fix: workflow knowledge publish decomposed sub type suffix

- __tests__/unit/lib/utils/fxpHelper.test.ts
- __tests__/unit/lib/utils/metadataDiff.test.ts
- src/metadata/a48.json
- src/metadata/v46.json
- src/metadata/v47.json
- src/metadata/v49.json
- src/metadata/v50.json
- src/metadata/v51.json
- src/metadata/v52.json
- src/metadata/v53.json
- src/metadata/v54.json
- src/metadata/v55.json
- src/metadata/v56.json
- src/metadata/v57.json
- src/metadata/v58.json
- src/metadata/v59.json
- src/metadata/v60.json
- src/metadata/v61.json
- src/metadata/v62.json
- src/post-processor/flowTranslationProcessor.ts
- src/service/inFileHandler.ts
- src/service/objectTranslationHandler.ts
- src/utils/fxpHelper.ts
- src/utils/metadataDiff.ts
---
Implement `layoutAssignments`, `loginHours` and `loginIpRanges` pruning algorithm.
For `layoutAssignments` the implementation outputs the previous list and new list difference based on object comparison
For `loginHours` and `loginIpRanges` the implementation outputs the new list only when the previous list and the new list are different.
---
closes #953
closes #948
> feat: prune `layoutAssignments`, `loginHours` and `loginIpRanges`

- src/metadata/v59.json
- src/metadata/v60.json
- src/metadata/v61.json
- src/metadata/v62.json
---
Add support for those metadata (starting at `v59`) : 
- [`ExternalClientApplication`](https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/meta_externalclientapplication.htm)
- [`ExtlClntAppGlobalOauthSettings`](https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/meta_extlclntappglobaloauthsettings.htm)
- [`ExtlClntAppOauthConfigurablePolicies`](https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/meta_extlclntappoauthconfigurablepolicies.htm)
- [`ExtlClntAppOauthSettings`](https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/meta_extlclntappoauthsettings.htm)
- [`ExtlClntAppConfigurablePolicies`](https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/meta_extlclntappconfigurablepolicies. …
> feat: add `ExternalClientApplication` metadata support

- src/metadata/v55.json
- src/metadata/v56.json
- src/metadata/v57.json
- src/metadata/v58.json
- src/metadata/v59.json
- src/metadata/v60.json
- src/metadata/v61.json
- src/metadata/v62.json
---
Support for :
[`ContextDefinition`](https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/meta_contextdefinition.htm?q=Context%20Definitions)
[`ExpressionSetMessageToken`](https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/meta_expressionsetmessagetoken.htm?q=ExpressionSetMessageToken)
[`ExpressionSetObjectAlias`](https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/meta_expressionsetobjectalias.htm?q=ExpressionSetMessageToken)
[`ProductSpecificationType`](https://developer.salesforce.com/docs/atlas.en-us.revenue_lifecycle_management_dev_guide.meta/revenue_lifecycle_management_dev_guide/sforce_api_objects_productspecificationtype.htm)
[`ProductSpecificationRecType`](https://developer.salesforce.com/docs/atlas.en-us.revenue_li …
> feat: add Expression Set metadatas support

- src/metadata/v55.json
- src/metadata/v56.json
- src/metadata/v57.json
- src/metadata/v58.json
- src/metadata/v59.json
- src/metadata/v60.json
- src/metadata/v61.json
- src/metadata/v62.json
---
This is an attempt to fix the metadata definition of `ExpressionSetDefinitionVersion`
---
closes #959
> fix: metadata definition for `ExpressionSetDefinitionVersion`

- src/metadata/v57.json
- src/metadata/v58.json
- src/metadata/v59.json
- src/metadata/v60.json
- src/metadata/v61.json
- src/metadata/v62.json
---
Add [ApplicationRecordTypeConfig](https://developer.salesforce.com/docs/atlas.en-us.psc_api.meta/psc_api/meta_applicationrecordtypeconfig.htm) metadata support
---
closes #968
> feat: add ApplicationRecordTypeConfig metadata support

- docs/migrating-to-v6.0.0.md
- src/commands/sgd/source/delta.ts
---
**Do not add** the [backward compatible](https://github.com/salesforcecli/cli/wiki/Migrate-Plugins-Built-for-sfdx#backward-compatibility) loglevel noop parameter
Explain in the migration guide how to set [loglevel](https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_dev_cli_log_messages.htm?q=log) now
cf this [cli-friends discussion](https://colladonsebas-yvi8516.slack.com/archives/C02R1NEG2G3/p1736332220137169)
---
closes #974
> fix: add `--loglevel` breaking change explanation

- messages/delta.md
- src/commands/sgd/source/delta.ts
---
Use `aliases` and `deprecateAliases` [backward compatible Flags attribut](https://github.com/salesforcecli/cli/wiki/Migrate-Plugins-Built-for-sfdx#backward-compatibility) to deal with our old parameters.
Remove the code we wrote to deal with that
> refactor: use native `aliases` and `deprecateAliases` sf cli feature

- .github/linters/.cspell.json
- .github/workflows/on-main-push.yml
- .github/workflows/reusable-build.yml
- .github/workflows/run-e2e-tests.yml
- README.md
- __tests__/unit/lib/adapter/GitAdapter.test.ts
- messages/delta.md
- package-lock.json
- package.json
- src/adapter/GitAdapter.ts
- src/commands/sgd/source/delta.ts
- src/constant/cliConstants.ts
- src/constant/gitConstants.ts
- src/post-processor/includeProcessor.ts
- src/utils/cliHelper.ts
---
Before it was possible to pass "." or ".." to either `--to` or `--from`. Our `rev-parse` check did not return errors but was not returning parsed revision as well.
This could lead to very strange behaviour and could mess with inFile comparison and "include" feature handling.
Now the plugin uses the parameter `--verify` for the `rev-parse` command which checks only for revision or alias of revision
Before error where not displayed when not using `--json`
Leaving the user interpret the result based on the exit code (not the most user friendly)
Now the plugin display the error with its message in the end or the success !
Disable SF CLI autoupdate and telemetry
> fix: check for commit ref for `--to` and `--from` parameters

- .github/workflows/on-merged-pull-request.yml
- .github/workflows/on-pull-request.yml
- .github/workflows/reusable-build.yml
- __tests__/unit/lib/metadata/MetadataRepositoryImpl.test.ts
- __tests__/unit/lib/service/customFieldHandler.test.ts
- package.json
- src/constant/metadataConstants.ts
- src/metadata/MetadataRepositoryImpl.ts
- src/metadata/v46.ts
- src/metadata/v47.ts
- src/metadata/v48.ts
- src/metadata/v49.ts
- src/metadata/v50.ts
- src/metadata/v51.ts
- src/metadata/v52.ts
- src/metadata/v53.ts
- src/metadata/v54.ts
- src/metadata/v55.ts
- src/metadata/v56.ts
- src/metadata/v57.ts
- src/metadata/v58.ts
- src/metadata/v59.ts
- src/metadata/v60.ts
- src/metadata/v61.ts
- src/metadata/v62.ts
- src/metadata/v63.ts
- src/service/customFieldHandler.ts
- src/service/decomposedHandler.ts
- src/types/metadata.ts
- stryker.conf.mjs
---
Now the code ensure the parent type file is included in the output folder
It just copy the parent file but do not include the parent type in the `package.xml`
---
closes #1000
> fix: parent file inclusion for Decomposed type

- src/metadata/v62.ts
- src/metadata/v63.ts
- src/metadata/v64.ts
---
Add support for ChoiceList metadata type since v62
https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/meta_choicelist.htm
---
No, we discovered this when adding ChoiceList metadata files to our repo for deployment
> feat: add ChoiceList metadata support
