scolladon/sfdx-git-delta

README.md
__mocks__/fs-extra.js
__mocks__/fs.js
__mocks__/git-state.js
__tests__/functional.test.js
__tests__/unit/index.test.js
__tests__/unit/lib/metadata/metadataManager.test.js
__tests__/unit/lib/packageConstructor.test.js
__tests__/unit/lib/service/typeHandlerFactory.test.js
bin/cli
index.js
lib/diffHandler.js
lib/metadata/metadata.js
lib/metadata/metadataManager.js
lib/packageConstructor.js
lib/service/inFolderHandler.js
lib/service/standardHandler.js
lib/service/typeHandlerFactory.js
package-lock.json
package.json

Add check for the input
And allow to get different api version or the latest available in the repo if the one specified at the command line is not available

Api version handling

---

lib/service/inFolderHandler.js
lib/service/inResourceHandler.js
lib/service/lightningHandler.js
lib/service/standardHandler.js
lib/service/subCustomObjectHandler.js

Need to have the parent folder when the parent folder is not present in the target env

Fix renaming inFolder metadata kind

---

__mocks__/fs-extra.js
__tests__/unit/index.test.js
index.js

Put package.xml in a package folder
Put destructiveChanges.xml with an empty package.xml in a destructiveChanges folder

output gracefully

---

index.js

More gracefully and less aggressively handle disk IO

Sequencing promise

---

lib/metadata/a48.json
lib/service/inResourceHandler.js
lib/service/typeHandlerFactory.js

Add metadata definition 
and type handler support for experience bundle
fixes #26

Experience Bundle support

---

lib/service/inFileHandler.js

resolves force-app/main/default/workflows/Task.workflow-meta.xml: meta.forEach is not a function
---
---
Single node metadata gets parsed as an object instead of array which the code is expecting.
Task.workflow-meta.xml
```
<?xml version="1.0" encoding="UTF-8"?>
<Workflow xmlns="http://soap.sforce.com/2006/04/metadata">
<fieldUpdates>
<fullName>Task_ActivityType</fullName>
<field>Type_for_Reporting__c</field>
<formula>TEXT(Type)</formula>
<name>Task.ActivityType</name>
<notifyAssignee>false</notifyAssignee>
<operation>Formula</operation>
<protected>false</protected>
<reevaluateOnChange>true</reevaluateOnChange>
</fieldUpdates>
<rules>
<fullName>Task Type update</fullName>
<actions>
<name>Task_ActivityType</name>
<type>FieldUpdate</type>
</actions>
<active>true</active> …
```

Single Node Metadata Processing

---

lib/utils/fileGitDiff.js
lib/utils/repoGitDiff.js

---
Minor improvement in the way the git command is called
Allow to have consistent output in every environment and setup
---
Add the --no-pager parameter to the git commands spawned
---
**Operating System:** macOs Mojave 10.14.6
**NPM version:** 6.14.8
**Node version:** v14.9.0
**sgd version:** 3.3.1
**git version:** 2.28.0

Add --no-pager parameter to git

---

package.json

---
---
_(Write your answer here.)_
Make retro compatibility possible for sgd cli

Add bin repository to artefact element of the npm package

---

.github/workflows/pull-request.yml
CONTRIBUTING.md

And improve Contributing guidelines
---
---
Fix pull request github action by building the app
---

Fix pull request builder

---

__mocks__/.forceignore
__tests__/unit/lib/utils/repoGitDiff.test.js
src/service/standardHandler.js
src/utils/repoGitDiff.js

---
---
Improve the filtering of ignored file by using path interpretable by non leading star ignore glob pattern
---
fix #81 
---
**Operating System:** MacOS Mojave 10.14.6
**Yarn version:** 1.22.10
**Node version:** v15.4.0
**sgd version:** 4.1.0
**git version:** …

Fix ignore sub folder

---

README.md

Adding an example to the readme, following https://github.com/scolladon/sfdx-git-delta/issues/91

Add compare example

---

README.md

Add an example of comparing branches in the README, to address https://github.com/scolladon/sfdx-git-delta/issues/101

Add compare branches example

---

.github/workflows/pull-request.yml

---
---
Add CodeCove and remove CodeClimate coverage report

Add CodeCove

---

.github/ISSUE_TEMPLATE/issue.md
.github/workflows/main.yml
tsconfig.json
yarn.lock

---
---
Reapply tsconfig.json extends to salesforce ts devconfig compilation settings
---
closes #120 
---
**git version:** git version 2.31.1
**sfdx version:** node-v14.16.0
**sgd plugin version:** 4.3.0

fix: silent SfdxCommand compilation issue

---

CONTRIBUTING.md

---
---
Improve CONTRIBUTING.md

docs: add commit linting and PR linting in the contribution guide

---

.github/workflows/main.yml
.github/workflows/pull-request.yml
.github/workflows/release.yml

and also cleanup the steps name
---
---
Add integration testing in the CI/CD.
It will help detects when a PR is breaking the plugin assembly
---
Will be added to the PR checks once merged.
Integration of this PR not relevant to a release
---
GH Action of this PR

feat: add integration test to CI

---

.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/release.yml

Allow release note generation and publishing from github
---
---
Embed the publishing workflow into a dispatch github action
---
To be tested in gh action

feat: create gh-action to trigger new release

---

README.md

Update README to inform Windows users of the need for double quotes
closes #134

docs: improve guidance for Windows users

---

src/metadata/a48.json
src/metadata/v46.json
src/metadata/v47.json
src/metadata/v49.json
src/metadata/v50.json
src/metadata/v51.json
src/metadata/v52.json

---
---
Add the MLDomain metadata type
---
Nop
---
Nop
---
Can be integrated in the next release
---
**sfdx version:** sfdx-cli/7.107.0 darwin-x64 node-v14.16.0
**sgd plugin version:** 4.61

feat: add MLDomain metadata

---

src/service/inFileHandler.js

---
---
Improve performance by
- exiting fast of the evaluation loop
- precompute information
- move methods to static
---
closes none
---
---
---
**sfdx version:** sfdx-cli/7.108.0 darwin-x64 node-v14.16.0
**sgd plugin version:** 4.7.0

perf: improve inFile handler performance

---

README.md

New badges for :
- npm
- codecov
---

docs: add npm badges

---

README.md

---
---
Remove non working badges

docs: cleanup badges

---

.github/CODEOWNERS

---
---
Add CODEOWNERS feature to this repository

feat: add CODEOWNERS and branch protection

---

src/metadata/v51.json
src/metadata/v52.json

---
---
Add metadata configuration related to `PlatformEventSubscriberConfig` metadata entity to metadata configuration file for APIs `51.0` and above
Documentation [here](https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/meta_platformeventsubscriberconfig.htm)
---
closes #202
~~- [ ] Jest test to check the fix is applied are added.~~
---
Retrieve `PlatformEventSubscriberConfig` metadata and play with the plugin !
---
Ready for the next release
---
**Operating System:** Darwin Kernel Version 19.6.0: Thu Sep 16 20:58:47 PDT 2021; root:xnu-6153.141.40.1~1/RELEASE_X86_64
**yarn version:** 1.22.15
**git version:** 2.33.1
**sfdx version:** node-v14.16.0
**sgd plugin version:** 4.9.1

feat: add PlatformEventSubscriberConfig support for APIs 51 and above

---

README.md

Remove mention to the legacy SGD command in the Readme.

chore: update install instructions

---

README.md
package.json
src/metadata/v53.json

---
---
Add the metadata file for API 53

build: add API 53

---

.github/workflows/check-dependencies.yml

---
---
Fix 'on' target and Name

fix: check dependency github action

---

CONTRIBUTING.md
PUBLISHING.md
README.md

---
---
Corrected spelling mistakes, typos, and grammar in Markdown files.
---
closes #
---
---
---
**Operating System:** …
**yarn version:** …
**node version:** …
**git version:** …
**sfdx version:** …
**sgd plugin version:** …

docs: spelling corrections in .md files

---

README.md
package.json

---
---
Fix xq query in README.md
Fixes * use case
Fixes one or no members in ApexClass

docs: fix xq query

---

README.md
package.json
src/metadata/v54.json

---
---
Add support for API 54

build: add API 54

---

CONTRIBUTING.md
PUBLISHING.md
README.md

---
---
Use [hemingway editor](https://hemingwayapp.com/) to simplify our documentation
Apply to :
- README.md
- CONTRIBUTING.md
- PUBLISHING.md

docs: simplify documentation

---

src/service/inFileHandler.js

---
---
Remove the duplicated xml header for in File delta generated

fix: xml header displayed twice for inFile delta generated

---

__tests__/unit/lib/service/inFolderHandler.test.js
src/service/inFileHandler.js
src/service/inFolderHandler.js
src/service/standardHandler.js
src/service/subCustomObjectHandler.js
yarn.lock

---
---
Make sure document file (even with special extension like `.png` for example) is copied alongside its meta file when its  meta file is modified
---
closes #272

fix: document file copy when metafile is modified

---

.github/ISSUE_TEMPLATE/enhancement.md
.github/ISSUE_TEMPLATE/issue.md
.github/PULL_REQUEST_TEMPLATE.md
PUBLISHING.md

---
---
Markdown files spelling correction.
---
closes #
---
---
---
**Operating System:** …
**yarn version:** …
**node version:** …
**git version:** …
**sfdx version:** …
**sgd plugin version:** …

fix: improve markdown files spelling

---

README.md

---
Fix the link on the table of content for the entry "Condition deployment on package.xml and destructiveChange content"

fix: link "Condition deployment" on TOC

---

.eslintignore
.github/workflows/pull-request.yml
.prettierignore

---
---
Add github integrated linter

feat: add github action linter

---

README.md
__tests__/unit/lib/service/waveHandler.test.js
package.json
src/service/standardHandler.js
src/service/waveHandler.js
yarn.lock

---
---
Make sure the extension is taken into account when copying metafile
---
closes #286

fix: wave meta file delta generation

---

.github/workflows/pull-request.yml
package.json
yarn.lock

---
---
Add multiple execution to the integration test CI step of the pull request automation:
- OS dimension with: Windows, Mac, Linux
- Node version dimension with: Node v14 and v16

build: implement matrix testing for integration test

---

README.md
package.json
yarn.lock

---
Introduce incremental deployment concept in the README
---

feat: introduce incremental deployment concept

---

README.md
package.json
src/metadata/v55.json

This pull request contains the ` v55.json` file under the `metadata` folder, which is similar to `v54.json` but containing as well support for the new `FlowTest` metadata type.
---
---
This Pull Requests aims to add support in order detect and include added/modified Flow Tests (included in Summer '22) in the result `package.xml`.
No.
---
The inclusion of the FlowTest elements in the output file package.xml when they are detected as added/modified by the command usage.
---
---
---
**Operating System:**  Windows 11
**yarn version:** 1.22.17
**node version:** v16.13.0
**git version:** 2.33.1.windows.1
**sfdx version:** sfdx-cli/7.160.0 win32-x64 node-v16.16.0
**sgd plugin version:** 5.3.0

build: add API 55 with FlowTest

---

src/metadata/v55.json

This pull request contains the addition of the `customindex`  metadata to the ` v55.json` file.
---
---
This Pull Requests aims to add support in order detect and include added custom indexes in the result `package.xml`. This metadata type is not officially documented yet, so not sure if it is a new feature or an undocumented behaviour leak. Read more about it [here](https://salesforce.stackexchange.com/questions/376766/create-custom-index-via-metadata-api-now-possible.
Maybe it is possible to ask this internally with the Salesforce Metadata API Product team before accepting this PR.
No.
---
The inclusion of the CustomIndex elements in the output file package.xml when they are detected as added/modified by the command usage.
---
---
---
**Operating System:**  Windows 11
**yarn version:** …

feat: add customindex metadata

---

__tests__/unit/lib/post-processor/flowTranslationProcessor.test.js
__tests__/unit/lib/utils/fxpHelper.test.js
package.json
src/post-processor/flowTranslationProcessor.js
src/service/inFileHandler.js
src/utils/fxpHelper.js
yarn.lock

---
---
Handling one parsed xml element to json resolving to object instead of array
Creating a method to deal with that aspect
Using this method in inFileHandler as well
Test has been added to cover this use case in the `flowTranslationProcessor.test.js` file
Tests have been added for the new `asArray` helper method
---
closes #342 
---
---
Tested in [sfdx playground](https://github.com/scolladon/sfdx-git-delta-reproduction-playground/tree/issue/321)

fix: handling xml parsing not returning array for one element

---

README.md
yarn.lock

---
---
Improve documentation for Windows user
Avoid using "^" character
Also remove usage in documentation
---
closes #348

docs: caret character git shorthand issue in windows environment

---

.github/workflows/manage-versions.yml

---
The github action checkout the sources to be able to run the move tag

fix: manage version github action

---

.github/workflows/manage-versions.yml

---
---
Use `yarn tag` instead of `yarn npm tag` (not working anymore)
Fix target variable insertion

fix: use `yarn tag` instead of `yarn npm tag`

---

.github/workflows/manage-versions.yml
PUBLISHING.md

---
---
Improve Admin experience by changing the name of the inputs, their descriptions and the possible value to put into

feat: improve parameters usage description

---

__tests__/unit/lib/post-processor/flowTranslationProcessor.test.js
__tests__/unit/lib/utils/ignoreHelper.test.js
__tests__/unit/lib/utils/repoGitDiff.test.js
src/post-processor/flowTranslationProcessor.js
src/utils/ignoreHelper.js
src/utils/repoGitDiff.js

---
---
Reapply business rule stating we should use the ignore pattern when `--ignore` is set and `--ignore-destructive` is not set.
Reapply the test that was previously validating this business rule
Refactor the service to be easier to unit test
Completely unit test the new ignore service (act as a spec)
Business rule is as follow:
| when                            | `--ignore` is set                                                                                            | `--ignore` is not set                                                                      |
|---------------------------------|-----------------------------------------------------------------------------------------------------------|---------------------------------------------------------------------------------- …

fix: ignore destructive with ignore when possible

---

SECURITY.md

---
---
Add a SECURITY.md file to explain
- how to log security issue
- which version are supported
---
nop

docs: create SECURITY.md file

---

__tests__/integration/domain.test.js
__tests__/unit/lib/service/inBundleHandler.test.js
src/metadata/a48.json
src/metadata/v47.json
src/metadata/v49.json
src/metadata/v50.json
src/metadata/v51.json
src/metadata/v52.json
src/metadata/v53.json
src/metadata/v54.json
src/metadata/v55.json
src/metadata/v56.json
src/service/inBundleHandler.js
src/service/typeHandlerFactory.js

---
---
Add LWR metadata definition
- [DigitalExperienceConfig](https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/meta_digitalexperienceconfig.htm)
- [DigitalExperienceBundle](https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/meta_digitalexperiencebundle.htm)
Create a handler for the DigitalExperienceBundle specificities
Implement spec of this new handler
Extend integration domain test for this new handler
---
closes #396
---
LWR template are beta
I don't know how to enable it and use in an org
---

feat: add digital experience metadata

---

package.json
src/metadata/v57.json

---
Bump Salesforce api version 57
Remove packing after generating new version as it is not required anymore because we do not have dynamic value refering the api version

feat: bump Salesforce api version 57

---

src/metadata/v55.json
src/metadata/v56.json
src/metadata/v57.json

---
Add industry cloud metadatas:
- `DecisionMatrixDefinition`
- `ExpressionSetDefinition`
from v55 to v57
---
closes #456

feat: add Industry Cloud metadata

---

commitlint.config.js
package.json
yarn.lock

---
migrate to the conventional config for commit lint to have `chore` commit type

fix: introduce chore commit type

---

.github/workflows/on-main-push.yml

---
fix version output usage in release automation

fix: version output usage in release automation

---

README.md

Signed-off-by: Marcellus Le <marcellusle@outlook.com>
Found some spelling typos, fixed them up.

docs: fix typos in readme (#483

---

src/metadata/v55.json
src/metadata/v56.json
src/metadata/v57.json

Added forecasting related metadata types.
---
---
closes #
---
Tested on Windows 11 with API version 57.
Not incrementing API version/release. To be decided up to the mantainers.
---

feat: add support for forecasting metadata types

---

package.json
src/metadata/v55.json
src/metadata/v56.json
src/metadata/v57.json
yarn.lock

---
Add new metadata:
- [AssessmentQuestion](https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/meta_assessmentquestion.htm)
- [AssessmentQuestionSet](https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/meta_assessmentquestionset.htm)
---
closes #541

feat: add FSC `AssessmentQuestion*` metadata

---

.github/workflows/on-pull-request.yml
.mocharc.json
CONTRIBUTING.md
package.json
yarn.lock

---
Create a workflow to run E2E test in all the environment we support

test: add E2E tests

---

README.md

---
Update node dependency information

docs: update node version information

---

__tests__/unit/lib/post-processor/flowTranslationProcessor.test.js
__tests__/unit/lib/utils/ignoreHelper.test.js
__tests__/unit/lib/utils/repoGitDiff.test.js
src/post-processor/flowTranslationProcessor.js
src/utils/ignoreHelper.js

---
Add default metadata to ignore when deleted
---
closes #620

feat: add metadata to ignore by default when deleted

---

package.json
src/metadata/v58.json
tooling/incrementApiVersion.sh
yarn.lock

---
add API v58 metadata definition

feat: add API v58 support

---

.github/workflows/manual-deprecate-versions.yml
.github/workflows/manual-manage-versions.yml
.github/workflows/on-main-push.yml

---
Fix `managed version` and `deprecate version` github actions
cf [documentation](https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages#:~:text=Please%20note%20that%20you%20need%20to%20set%20the%20registry%2Durl%20to%20https%3A//registry.npmjs.org/%20in%20setup%2Dnode%20to%20properly%20configure%20your%20credentials.)

ci: fix registry setup when interacting with npm

---

__tests__/unit/lib/utils/metadataDiff.test.js
package.json
src/utils/metadataDiff.js
yarn.lock

---
Fix empty check
Improve spec
---
closes #

fix: empty inFile metadata detection

---

src/metadata/v57.json
src/metadata/v58.json
src/metadata/v59.json

---
Add `OmniSupervisorConfig` metadata description since `v57`
---
closes #722

feat: add `OmniSupervisorConfig` metadata support

---

src/metadata/v54.json
src/metadata/v55.json
src/metadata/v56.json
src/metadata/v57.json
src/metadata/v58.json
src/metadata/v59.json
src/service/typeHandlerFactory.ts

Add `MarketingAppExtension` in file metadata type
with `MarketingAppExtActivity` sub type
---
---
closes #732

feat: support `MarketingAppExtension` metadata type

---

.github/linters/.cspell.json
.github/workflows/manual-deprecate-versions.yml
.github/workflows/manual-manage-versions.yml
.github/workflows/on-main-push.yml
.github/workflows/on-pull-request.yml
.github/workflows/reusable-build.yml
.mega-linter.yml
.release-please-manifest.json
README.md
lychee.toml
src/utils/fxpHelper.ts

---
Improve `fast-xml-parser` xml builder configuration
---
closes #737 
---
---

fix: boolean attribute and comment xml parsing

---

src/locales/en.ts

---
Add tips in CI/CD context about the git SHA pointer error

fix: add fetch depth tips for git sha pointer error

---

src/metadata/v55.json
src/metadata/v56.json
src/metadata/v57.json
src/metadata/v58.json
src/metadata/v59.json

---
Add `MessagingChannel` metadata support
---
closes #753

feat: add `MessagingChannel` metadata support

---

src/metadata/v60.json

---
Add `v60` metadata definition file

feat: add `Spring'24` release preview support

---

package.json
yarn.lock

---
add `@salesforce/core` dependency explicitly
---
closes #804

fix: add `@salesforce/core` missing dependency

---

stryker.conf.mjs

---
Change the file patterns for the file to mutate
Should have been done when migrating to typescript

build: fix mutation testing files pattern

---

.github/workflows/on-main-push.yml
.github/workflows/on-pull-request.yml
.github/workflows/run-e2e-tests.yml

---
Create a workflow to run e2e test, taking the channel to install
At the PR level, execute e2e test from the package created for QA (better than from sources because it test also the publishing)
On main, execute e2e test with the version created

refactor: centralize e2e test process definition

---

.github/workflows/on-merged-pull-request.yml
.github/workflows/on-pull-request.yml
.github/workflows/run-e2e-tests.yml
package.json

---
Clean deprecated dist-tag and dev npm package generated from merged pull request

build: clean up outdated npm dev package

---

.github/workflows/on-merged-pull-request.yml
package.json
yarn.lock

---
Update the PR when merged so the dev package message is deleted as the related packages are deprecated and the dist-tag is removed

build: delete PR dev package message after merge

---

.github/workflows/on-main-push.yml
.github/workflows/on-merged-pull-request.yml
.github/workflows/on-pull-request.yml

---
execute perf test when updating release

build: execute perf test when updating release

---

.github/workflows/on-merged-pull-request.yml

---
fix github action execution

build: fix github action execution

---

README.md

---
Add a performance badge in the readme to redirect to the performance dashboard

docs: add a performance badge

---

package.json
src/metadata/v61.json

---
---
Support API version 61 in preview

feat: support preview api version `61`

---

.github/workflows/on-main-push.yml
PUBLISHING.md

---
upgrade release please CI job
use the new repository vs the old deprecated one

build: upgrade release please CI job

---

src/metadata/v62.json

---
add `Winter '25` `(v62)` release preview support

feat: add `Winter '25` `(v62)` release preview support

---

README.md

---
Adds complementary plugins to the SGD README.
Per discussion in https://github.com/scolladon/sfdx-git-delta/issues/913
---
Documentation only update.
---
---

docs: reference complementary plugins

---

src/metadata/v50.json
src/metadata/v51.json
src/metadata/v52.json
src/metadata/v53.json
src/metadata/v54.json
src/metadata/v55.json
src/metadata/v56.json
src/metadata/v57.json
src/metadata/v58.json
src/metadata/v59.json
src/metadata/v60.json
src/metadata/v61.json
src/metadata/v62.json

---
add BriefCaseDefinition metadata support
---
closes #925

feat: add BriefCaseDefinition metadata support

---

.ls-lint.yml
README.md
src/commands/sgd/source/delta.ts

---
Communicate inside the plugin the new v6 version
- In the README
- In the cli itself as a warning

feat: communicate new v6 plugin version

---

__tests__/integration/services.test.ts
src/metadata/a48.json
src/metadata/v46.json
src/metadata/v47.json
src/metadata/v49.json
src/metadata/v50.json
src/metadata/v51.json
src/metadata/v52.json
src/metadata/v53.json
src/metadata/v54.json
src/metadata/v55.json
src/metadata/v56.json
src/metadata/v57.json
src/metadata/v58.json
src/metadata/v59.json
src/metadata/v60.json
src/metadata/v61.json
src/metadata/v62.json

---
Update metadata file descriptions to contains actual file extension and containing folder for workflow decomposed type
---
closes #941 
---
Follow the instructions from #941 description

fix: decomposed workflow sub types definition

---

__tests__/unit/lib/adapter/GitAdapter.test.ts
__tests__/unit/lib/service/standardHandler.test.ts
src/adapter/GitAdapter.ts
src/service/standardHandler.ts

---
Improve array concatenation with very large volume of lines
Secure path sent to git for file listing
Secure regex when path starts with folder (repo is current folder)

fix: implementation issues with large repository

---

package-lock.json
package.json
src/commands/sgd/source/delta.ts

---
Display warning message properly using the Error message it contains
---
closes #980
closes #982

fix: how warnings are displayed

---

src/metadata/v52.ts
src/metadata/v53.ts
src/metadata/v54.ts
src/metadata/v55.ts
src/metadata/v56.ts
src/metadata/v57.ts
src/metadata/v58.ts
src/metadata/v59.ts
src/metadata/v60.ts
src/metadata/v61.ts
src/metadata/v62.ts
src/metadata/v63.ts
src/metadata/v64.ts

---
Add `DocumentGenerationSetting` metadata support
---
closes #1073

feat: add `DocumentGenerationSetting` metadata support

---

src/metadata/v61.ts
src/metadata/v62.ts
src/metadata/v63.ts
src/metadata/v64.ts

---
add `DocumentTemplate` metadata support since `v61`
---
closes #1034
closes #1076

feat: add `DocumentTemplate` metadata support
